### ISSUE TITLE
IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by rafitamolin** [rupansh/OpenDistortBot#1]
Tried with relative and absolute paths:

```Traceback (most recent call last):
  File "distortion_bot.py", line 41, in <module>
    bot.polling()
  File "/usr/local/lib/python2.7/dist-packages/telebot/__init__.py", line 389, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "/usr/local/lib/python2.7/dist-packages/telebot/__init__.py", line 413, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "/usr/local/lib/python2.7/dist-packages/telebot/util.py", line 108, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "/usr/local/lib/python2.7/dist-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "distortion_bot.py", line 35, in photudl
    photo = open('result/'+file_name, 'rb')
IOError: [Errno 2] No such file or directory: 'result/2.jpg'
```

&

```Traceback (most recent call last):
  File "distortion_bot.py", line 41, in <module>
    bot.polling()
  File "/usr/local/lib/python2.7/dist-packages/telebot/__init__.py", line 389, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "/usr/local/lib/python2.7/dist-packages/telebot/__init__.py", line 413, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "/usr/local/lib/python2.7/dist-packages/telebot/util.py", line 108, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "/usr/local/lib/python2.7/dist-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "distortion_bot.py", line 35, in photudl
    photo = open('/home/twitter/telegram/OpenDistortBot/result/'+file_name, 'rb')
IOError: [Errno 2] No such file or directory: '/home/twitter/telegram/OpenDistortBot/result/82.jpg'
```

**Comment by rupansh** [comment]
hey! I thought no one was going to use this lol
Anyways i plan to rewrite the bot in aiogram(Will probably take 15 minutes) since its async.
Also you need imagemagick installed for liquid rescale! If you don't have it then it should fix the issue. also i tested the bot in python3 so try your luck there if you have imagemagick :)

**Comment by rupansh** [comment]
@rafitamolin I completed the rewrite. You should be able to use the bot just fine with ImageMagick 7 and python3.7 !

**Comment by rafitamolin** [comment]
@rupansh Now the script works just fine with the command `python3.7 distortion_bot.py` and the bot replies to the /help command but it doesn't distort any image, even though I installed liblqr-1.0-dev and built ImageMagick 7 from source, strange :(

**Comment by rupansh** [comment]
@rafitamolin you have to install liblqr-1.0-dev first, then install imagemagick. If yoj did that try
> sudo ldconfig /usr/local/lib

Also send me the complete log if it still doesnt distort
