### ISSUE TITLE
Unable to get it to work.

### ISSUE THREAD

**Issue by roddylab** [rupansh/OpenDistortBot#2]
This is reply to:
/distort
Bot doesn't react on pictures sent. 
```
~/OpenDistortBot# sudo python3 distortion_bot.py
Task exception was never retrieved
future: <Task finished coro=<Dispatcher._process_polling_updates() done, defined at /usr/local/lib/python3.7/dist-packages/aiogram-2.1.1.dev1-py3.7.egg/aiogram/dispatcher/dispatcher.py:274> exception=AttributeError("'NoneType' object has no attribute 'photo'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/aiogram-2.1.1.dev1-py3.7.egg/aiogram/dispatcher/dispatcher.py", line 282, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/usr/local/lib/python3.7/dist-packages/aiogram-2.1.1.dev1-py3.7.egg/aiogram/dispatcher/dispatcher.py", line 142, in process_updates
    return await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.7/dist-packages/aiogram-2.1.1.dev1-py3.7.egg/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/usr/local/lib/python3.7/dist-packages/aiogram-2.1.1.dev1-py3.7.egg/aiogram/dispatcher/dispatcher.py", line 162, in process_update
    return await self.message_handlers.notify(update.message)
  File "/usr/local/lib/python3.7/dist-packages/aiogram-2.1.1.dev1-py3.7.egg/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "distortion_bot.py", line 49, in dodistort
    if message.reply_to_message.photo or message.reply_to_message.sticker:
AttributeError: 'NoneType' object has no attribute 'photo'
```

**Comment by rupansh** [comment]
You have to reply to the photo and not use /distort below the pic. My bad anyways. I forgot to add checks for NoneType replies

**Comment by roddylab** [comment]
Thanks dad, all works now, except I was receiving some errors about that file I sent was not saved in result folder, but as I have seen it was just saving near the distortion_bot.py file. So I removed "result\" and everything else like this leaving just: {fname} from everywhere and it works nice.
